export {default as About} from './_About'
export {default as Landing} from './_Landing'
export {default as NotFound} from './_NotFound'
export {default as Projects} from './_Projects'
export {default as Skills} from './_Skills'
